title: "Awesome Copywriting"
description: "A curated list of the world's best copywriters, copy examples, frameworks, swipe files, and resources."
url: "https://guilhermealbert.github.io"
baseurl: "/awesome-copywriting"
theme: "jekyll-theme-cayman"
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
markdown: "kramdown"
highlighter: "rouge"
kramdown:
  input: GFM
exclude:
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE
  - .github/
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
